import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header, IntlProvider } from "smarthr-ui";
import "./globals.css";
import 'smarthr-ui/smarthr-ui.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <IntlProvider locale="ja">
      <html
        lang="ja"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <Header />
          {children}
        </body>
      </html>
    </IntlProvider>
  );
}
